apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lkoo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0073-tenant/ci1t-830-0073-app/devfile-sample-lkoo@sha256:7a6858cc1e1dc555052420f56cad6468b8cbba769085fedb27b9f779d76f2fae
        name: my-nodejs
        resources: {}
status: {}
